-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
--
--

-- File: ~/.config/nvim/lua/config/autocmds.lua

-- Autocmd for Python files

--vim.api.nvim_create_autocmd("FileType", {
--  pattern = "rust",
--  callback = function()
--    vim.cmd("colorscheme nord")
--  end,
--})
--
--vim.api.nvim_create_autocmd("FileType", {
--  pattern = "python",
--  callback = function()
--    vim.cmd("colorscheme nord")
--  end,
--})
--
--vim.api.nvim_create_autocmd("FileType", {
--  pattern = "go",
--  callback = function()
--    vim.cmd("colorscheme monokai")
--  end,
--})
--
--vim.api.nvim_create_autocmd("FileType", {
--  pattern = "c",
--  callback = function()
--    vim.schedule(function()
--      vim.cmd("colorscheme gruvbox")
--    end)
--  end,
--})
--
---- Autocmd for Rust files
--vim.api.nvim_create_autocmd("FileType", {
--  pattern = "verilog",
--  callback = function()
--    vim.schedule(function()
--      vim.cmd("colorscheme catppuccin-mocha")
--    end)
--  end,
--})
