return {
  --  {
  --    -- https://github.com/ellisonleao/gruvbox.nvim
  --    "ellisonleao/gruvbox.nvim",
  --    opts = {
  --      transparent_mode = false,
  --      dim_inactive = true,
  --    },
  --  },
  --  --{ "rebelot/kanagawa.nvim" },
  --  { "catppuccin/nvim", name = "catppuccin", lazy = false },
  --  { "rose-pine/neovim", name = "rose-pine" },
  --  { "sainnhe/everforest" },
  --  { "bluz71/vim-nightfly-colors" },
  --  { "NLKNguyen/papercolor-theme" },
  --  { "romainl/Apprentice" },
  --
  --  -- Configure LazyVim to load colorscheme
  --  {
  --    "LazyVim/LazyVim",
  --    opts = {
  --      colorscheme = "gruvbox",
  --    },
  --  },
}
