return {
  --  --- requests the plugin to be installed
  --  "veryl-lang/veryl.vim",
  --
  --  --- use vim callback function to edit your config file, but from here. keeps it self contained.
  --  ft = { "veryl" },
  --  config = function()
  --    --- define the filetype
  --    vim.filetype.add({
  --      extension = { veryl = "veryl" },
  --    })
  --
  --    --- when you write files that are this format,
  --    vim.api.nvim_create_autocmd("BufWritePost", {
  --      pattern = "*.veryl",
  --      callback = function()
  --        local file = vim.fn.expand("%:p")
  --        local output = {}
  --
  --        --- run the autoformatter,
  --        --- reload buffer on success
  --        --- forward error to nvim ui on error
  --        vim.fn.jobstart({ "veryl", "fmt", file }, {
  --          stdout_buffered = true,
  --          stderr_buffered = true,
  --          on_stdout = function(_, data)
  --            if data then
  --              vim.list_extend(output, data)
  --            end
  --          end,
  --          on_stderr = function(_, data)
  --            if data then
  --              vim.list_extend(output, data)
  --            end
  --          end,
  --          on_exit = function(_, code)
  --            vim.schedule(function()
  --              if code == 0 then
  --                vim.cmd("checktime")
  --                vim.cmd("edit!")
  --                vim.cmd("redraw!")
  --              else
  --                vim.notify(table.concat(output, "\n"), vim.log.levels.ERROR, { title = "veryl fmt failed" })
  --              end
  --            end)
  --          end,
  --        })
  --      end,
  --    })
  --  end,
}
